--create table course (
--    id bigint not null,
--    name varchar(255) not null,
--    author varchar(255) not null,
--    primary key(id)
--);
--
--create table department (
--    id bigint not null,
--    name varchar(255) not null,
--    primary key(id)
--);
--
--create table user (
--    id bigint not null,
--    name varchar(255) not null,
--    email varchar(255) not null,
--    primary key(id)
--);
--
--create table department (
--    id bigint not null,
--    name varchar(255) not null,
--    description varchar(255) not null,
--    isCompleted
--    primary key(id)
--);